---
- name: "Populate needed secrets and env vars"
  hosts: localhost

  tasks:
    # contact_email is a file that just contains one line:
    # ADMIN_EMAIL=email@example.com
    - name: "Create contactemail secret"
      shell: "oc create secret generic contactemail --from-env-file=contact_email"
      register: contact_email_created

    - name: "Create contact email env var"
      shell: "oc env --from=secret/contactemail dc/shinodev"
      when: contact_email_created is defined

    - name: "Create cookie secret"
      shell: "oc create secret generic cookiesecret --from-env-file=cookie_secret"
      register: cookie_secret_created

    - name: "Create cookie env var"
      shell: "oc env --from=secret/cookiesecret dc/shinodev"
      when: cookie_secret_created is defined
