---
- name: "Populate needed secrets and env vars"
  hosts: localhost

  tasks:
    #- name: "Create contact form secret"
    #  shell: "oc secrets new contactform credentials=contact_form_creds"

    #- name: "Create google oauth secret"
    #  shell: "oc secrets new googleoauth oauth=google_auth_creds"

    # contact_email is a file that just contains one line:
    # ADMIN_EMAIL=email@example.com
    - name: "Create contactemail secret"
      shell: "oc create secret generic contactemail --from-env-file=contact_email"
      register: contact_email_created

    - name: "Create contact email env var"
      shell: "oc env --from=secret/contactemail dc/dedgar"
      when: contact_email_created is defined

    - name: "Create cookie secret"
      shell: "oc create secret generic cookiesecret --from-env-file=cookie_secret"
      register: cookie_secret_created

    - name: "Create cookie env var"
      shell: "oc env --from=secret/cookiesecret dc/dedgar"
      when: cookie_secret_created is defined

    - name: "Create oauth secret"
      shell: "oc create secret generic oauthsecret --from-env-file=google_env"
      register: oauth_secret_created

    - name: "Create oauth env var"
      shell: "oc env --from=secret/oauthsecret dc/dedgar"
      when: oauth_secret_created is defined
